# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
# Your code here
import numpy as np
import random

def fill_matrix(matrix):

    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
    
    return matrix

A = np.zeros((3, 2))
A = fill_matrix(A)

B = np.zeros((2, 1))
B = fill_matrix(B)

C = np.zeros((2, 1))
C = fill_matrix(C)

LHS = A.dot(B + C)
RHS = A.dot(B) + A.dot(C)

print (LHS == RHS)

[[ True]
 [ True]
 [ True]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [3]:
# Your code here 
A = np.zeros((3, 2))
A = fill_matrix(A)

B = np.zeros((2, 2))
B = fill_matrix(B)

C = np.zeros((2, 1))
C = fill_matrix(C)

LHS = A.dot(B.dot(C))
RHS = (A.dot(B)).dot(C)

LHS == RHS

array([[ True],
       [ True],
       [ True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [4]:
# Your code here 
A = np.zeros((2, 2))
A = fill_matrix(A)

B = np.zeros((2, 2))
B = fill_matrix(B)

LHS = A.dot(B)
RHS = B.dot(A)

LHS == RHS

array([[False, False],
       [False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [5]:
# Your code here
x = np.zeros((3, 1))
x = fill_matrix(x)

y = np.zeros((3, 1))
y = fill_matrix(y)

LHS = np.transpose(x).dot(y)
RHS = np.transpose(y).dot(x)

LHS == RHS

array([[ True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [6]:
# Your code here 
A = np.zeros((4, 2))
A = fill_matrix(A)

B = np.zeros((2, 2))
B = fill_matrix(B)

LHS = np.transpose(A.dot(B))
RHS = np.transpose(B).dot(np.transpose(A))

LHS == RHS

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 